#DataBase connect
$db = SQLite3::Database.open "test.db"
$db.execute "CREATE TABLE IF NOt EXISTS SCAN (
  TIMESTART PRIMARY KEY,
  PARAMETRES TEXT,
  TIMEEND TEXT,
  STATUS TEXT,
  HOSTSUMM INTEGER,
  TIMESUMM INTEGER
);"
$db.execute "CREATE TABLE IF NOt EXISTS HOSTS (
  TIMESTART TEXT,
  TIMEEND TEXT,
  ID INTEGER PRIMARY KEY,
  STATUS TEXT,
  PORTSUMM INTEGER,
  IPHOST TEXT,
  HOSTNAME TEXT,
  HOSTMAC TEXT,
  OSID TEXT,
  FOREIGN KEY(TIMESTART) REFERENCES SCAN(TIMESTART),
  FOREIGN KEY(OSID) REFERENCES OS(ID)
);"

$db.execute "CREATE TABLE IF NOT EXISTS PORTS (
  ID TEXT PRIMARY KEY,
  TIMESTART TEXT,
  PORTNUM INTEGER,
  PROTOCOL TEXT,
  STATE TEXT,
  SERVICE TEXT,
  PORTVERSION TEXT,
  IDHOST TEXT,
  FOREIGN KEY(IDHOST) REFERENCES HOSTS(ID),
  FOREIGN KEY(PORTVERSION) REFERENCES SERVICE(ID)
)"

$db.execute "CREATE TABLE IF NOT EXISTS OS (
  ID INTEGER PRIMARY KEY,
  DEVTYPE TEXT,
  RUNNING TEXT,
  OSDETAIL TEXT
)"
$db.execute "CREATE TABLE IF NOT EXISTS SERVICEVERSION (
  ID INTEGER PRIMARY KEY,
  NAME TEXT,
  DESCRIBE TEXT,
  VULNERABILITY TEXT,
  ADDTIME TEXT
)"
